# Collaboration and Competition

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the third project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Tennis.app"`
- **Windows** (x86): `"path/to/Tennis_Windows_x86/Tennis.exe"`
- **Windows** (x86_64): `"path/to/Tennis_Windows_x86_64/Tennis.exe"`
- **Linux** (x86): `"path/to/Tennis_Linux/Tennis.x86"`
- **Linux** (x86_64): `"path/to/Tennis_Linux/Tennis.x86_64"`
- **Linux** (x86, headless): `"path/to/Tennis_Linux_NoVis/Tennis.x86"`
- **Linux** (x86_64, headless): `"path/to/Tennis_Linux_NoVis/Tennis.x86_64"`

For instance, if you are using a Mac, then you downloaded `Tennis.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Tennis.app")
```

In [2]:
env = UnityEnvironment(file_name="Tennis.app")

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: TennisBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, two agents control rackets to bounce a ball over a net. If an agent hits the ball over the net, it receives a reward of +0.1.  If an agent lets a ball hit the ground or hits the ball out of bounds, it receives a reward of -0.01.  Thus, the goal of each agent is to keep the ball in play.

The observation space consists of 8 variables corresponding to the position and velocity of the ball and racket. Two continuous actions are available, corresponding to movement toward (or away from) the net, and jumping. 

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents 
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 2
Size of each action: 2
There are 2 agents. Each observes a state with length: 24
The state for the first agent looks like: [ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.         -6.65278625 -1.5
 -0.          0.          6.83172083  6.         -0.          0.        ]


### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [ ]:
from ppo import run_ppo

run_ppo(env)

> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(102)run_ppo()
    100   for update in range(1, N_ROLLOUTS + 1):
    101     import pdb; pdb.set_trace()
--> 102     print(
    103         f"update {update}/{N_ROLLOUTS}. Last update in {time.time() - time_checkpoint}s"
    104     )

ipdb> observations
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         -7.3899, -1.5000, -0.0000,  0.0000,  6.8317,  5.9961, -0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         -6.7002, -1.5000,  0.0000,  0.0000, -6.8317,  5.9961,  0.0000,  0.0000]])
ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(103)run_ppo()
    101     import pdb; pdb.set_trace()
    102     print(
--> 103   

ipdb> p env_info
ipdb> p env_info.done
*** AttributeError: 'BrainInfo' object has no attribute 'done'
ipdb> p env_info.local_done
[False, False]
ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(113)run_ppo()
    111       env_info = env.step(actions.cpu().numpy())[brain_name]
    112       dones = env_info.local_done
--> 113       rewards = np.array(env_info.rewards)
    114       rewards[np.isnan(rewards)] = 0
    115 

ipdb> p env_info.rewards
[0.0, 0.0]
ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(114)run_ppo()
    112       dones = env_info.local_done
    113       rewards = np.array(env_info.rewards)
--> 114       rewards[np.isnan(rewards)] = 0
    115 
    116       rollout.observations[t] = observations

ipdb> ll
     67 def run_ppo(env):
     68   """Trains a ppo agent in an environment.
     69 
     70   Saves model and learning curve checkpoints.
     71   """
     72   brain_name = env.b

ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(116)run_ppo()
    114       rewards[np.isnan(rewards)] = 0
    115 
--> 116       rollout.observations[t] = observations
    117       rollout.actions[t] = actions
    118       rollout.rewards[t] = torch.Tensor(rewards).to(device)

ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(117)run_ppo()
    115 
    116       rollout.observations[t] = observations
--> 117       rollout.actions[t] = actions
    118       rollout.rewards[t] = torch.Tensor(rewards).to(device)
    119       rollout.dones[t] = torch.Tensor([dones]).to(device)

ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(118)run_ppo()
    116       rollout.observations[t] = observations
    117       rollout.actions[t] = actions
--> 118       rollout.rewards[t] = torch.Tensor(rewards).to(device)
    119       rollout.dones[t] = torch.Tensor([dones]).to(devi

ipdb> p current_returns
array([0., 0.])
ipdb> current_returns[dones]
array([], dtype=float64)
ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(126)run_ppo()
    124       current_returns += env_info.rewards
    125       scores.extend(current_returns[dones])
--> 126       current_returns[dones] = 0
    127 
    128       if any(dones):

ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(128)run_ppo()
    126       current_returns[dones] = 0
    127 
--> 128       if any(dones):
    129         env_info = env.reset(train_mode=True)[brain_name]
    130 

ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(131)run_ppo()
    129         env_info = env.reset(train_mode=True)[brain_name]
    130 
--> 131       observations = torch.Tensor(env_info.vector_observations).to(device)
    132       # observations[torch.isnan(next_observations)] = 0
    133 

ipdb> n
> /Users/hoon

ipdb> p t
14
ipdb> p current_returns
array([0., 0.])
ipdb> p dones
[True, True]
ipdb> p current_returns
array([0., 0.])
ipdb> p scores
[0.0, -0.009999999776482582]
ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(131)run_ppo()
1   129         env_info = env.reset(train_mode=True)[brain_name]
    130 
--> 131       observations = torch.Tensor(env_info.vector_observations).to(device)
    132       # observations[torch.isnan(next_observations)] = 0
    133 

ipdb> until 135
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(129)run_ppo()
    127 
    128       if any(dones):
1-> 129         env_info = env.reset(train_mode=True)[brain_name]
    130 
    131       observations = torch.Tensor(env_info.vector_observations).to(device)

ipdb> clear 1
Deleted breakpoint 1 at /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py:129
ipdb> until 135
> /Users/hoonji/Workspace/rlnd/deep-reinforcement

ipdb> td_errors + (1.0 - rollout.dones[t]) * GAMMA * GAE_LAMBDA * z
tensor([-0.0100, -0.0100])
ipdb> p td_errors
tensor([-0.0100, -0.0100])
ipdb> n
> /Users/hoonji/Workspace/rlnd/deep-reinforcement-learning/p3_collab-compet/ppo.py(144)run_ppo()
    142           1.0 - rollout.dones[t]) * GAMMA * next_values - rollout.values[t]
    143       z = td_errors + (1.0 - rollout.dones[t]) * GAMMA * GAE_LAMBDA * z
--> 144       rollout.advantages[t] = z
    145 
    146     for epoch in range(UPDATE_EPOCHS):

ipdb> p z
tensor([-0.0100, -0.0100])


In [ ]:
def copy_model_and_plot_learning_curve():
    import pickle
    import matplotlib.pyplot as plt
    from collections import deque
    import os
    import datetime
    import shutil
    
    datetime_stamp = datetime.datetime.now().strftime('%y%m%d_%H%M')
    plot_path = f'checkpoints/{datetime_stamp}'
    
    if not os.path.exists(plot_path):
        os.makedirs(plot_path)
    else:
        print(f'directory {plot_path} already exists')
        return
    
    shutil.copyfile(f'{brain_name}_scores.pickle', f'{plot_path}/scores.pickle')
    shutil.copyfile(f'{brain_name}_model_checkpoint.pickle', f'{plot_path}/model.pickle')

    with open(f'{plot_path}/scores.pickle', 'rb') as f:
        total_rewards = pickle.load(f)

    smoothed = []
    queue = deque([], maxlen=10)
    for r in total_rewards:
        queue.append(r)
        smoothed.append(sum(queue)/len(queue))
    fig,ax = plt.subplots()
    ax.plot(smoothed)
    ax.set_xlabel('total episodes (across all agents)')
    plt.savefig(f'{plot_path}/learning_curve.png')
    plt.show()
copy_model_and_plot_learning_curve()