# Collaboration and Competition

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the third project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Tennis.app"`
- **Windows** (x86): `"path/to/Tennis_Windows_x86/Tennis.exe"`
- **Windows** (x86_64): `"path/to/Tennis_Windows_x86_64/Tennis.exe"`
- **Linux** (x86): `"path/to/Tennis_Linux/Tennis.x86"`
- **Linux** (x86_64): `"path/to/Tennis_Linux/Tennis.x86_64"`
- **Linux** (x86, headless): `"path/to/Tennis_Linux_NoVis/Tennis.x86"`
- **Linux** (x86_64, headless): `"path/to/Tennis_Linux_NoVis/Tennis.x86_64"`

For instance, if you are using a Mac, then you downloaded `Tennis.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Tennis.app")
```

In [2]:
env = UnityEnvironment(file_name="Tennis.app")

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: TennisBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, two agents control rackets to bounce a ball over a net. If an agent hits the ball over the net, it receives a reward of +0.1.  If an agent lets a ball hit the ground or hits the ball out of bounds, it receives a reward of -0.01.  Thus, the goal of each agent is to keep the ball in play.

The observation space consists of 8 variables corresponding to the position and velocity of the ball and racket. Two continuous actions are available, corresponding to movement toward (or away from) the net, and jumping. 

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=False)[brain_name]

# number of agents 
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
# print('The state for the first agent looks like:', states[0],states[1])
print(env_info.vector_observations[:,:8])
print(env_info.vector_observations[:,8:16])
print(env_info.vector_observations[:,16:24])

from numpy.random import default_rng
rng = default_rng()

invariant = set(range(8))
a = np.array([0,1,0,0])
print('action', a)
# for _ in range(30):
#     #a = np.random.rand(4)
#     #a = np.array([1,1,1,1])
#     #a = np.array([1,-1,1,-1])
#     #a = np.array([[0,1],[-1,0]])
    
#     env_info = env.step(a)[brain_name]
#     #print(env_info.vector_observations[:,:8])
#     #print(env_info.vector_observations[:,8:16])
#     print(env_info.vector_observations[:,16:24])
#     for index in [8,16,24]:
#         cur_invariant = set((env_info.vector_observations[0,index-8:index] == env_info.vector_observations[1,index-8:index]).nonzero()[0].flatten())
#         invariant &= cur_invariant
#     #print('invariant', invariant)
#     import pdb; pdb.set_trace()
#     if any(env_info.local_done):
#         break

Number of agents: 2
Size of each action: 2
There are 2 agents. Each observes a state with length: 24
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[-6.65278625 -1.5        -0.          0.          6.83172083  6.
  -0.          0.        ]
 [-6.4669857  -1.5         0.          0.         -6.83172083  6.
   0.          0.        ]]
action [0 1 0 0]


### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [ ]:
from ppo import run_ppo

run_ppo(env)

Beginning training loop
update 10/50000. finished 613 episodes. Last update in 26.78339195251465s
average of last 100 returns: 0.002000000216066837
max of last 100: 0.10000000149011612
update 20/50000. finished 1217 episodes. Last update in 25.890764951705933s
average of last 100 returns: 0.0010000002011656762
max of last 100: 0.10000000149011612
update 30/50000. finished 1812 episodes. Last update in 31.803087949752808s
average of last 100 returns: 0.0010000002011656762
max of last 100: 0.10000000149011612
update 40/50000. finished 2398 episodes. Last update in 44.36111092567444s
average of last 100 returns: 0.0030000002309679987
max of last 100: 0.10000000149011612
update 50/50000. finished 3001 episodes. Last update in 35.175589084625244s
average of last 100 returns: 0.0030000002309679987
max of last 100: 0.10000000149011612
update 60/50000. finished 3607 episodes. Last update in 30.31537890434265s
average of last 100 returns: -0.0029999998584389685
max of last 100: 0.09000000171363

update 510/50000. finished 28611 episodes. Last update in 26.16400671005249s
average of last 100 returns: 0.006000000275671482
max of last 100: 0.10000000149011612
update 520/50000. finished 29149 episodes. Last update in 27.903153896331787s
average of last 100 returns: 0.006000000275671482
max of last 100: 0.10000000149011612
update 530/50000. finished 29682 episodes. Last update in 27.532336711883545s
average of last 100 returns: 0.007000000290572643
max of last 100: 0.10000000149011612
update 540/50000. finished 30230 episodes. Last update in 28.995672941207886s
average of last 100 returns: 0.0030000002309679987
max of last 100: 0.10000000149011612
update 550/50000. finished 30786 episodes. Last update in 27.12899136543274s
average of last 100 returns: 0.005000000260770321
max of last 100: 0.10000000149011612
update 560/50000. finished 31341 episodes. Last update in 25.847254037857056s
average of last 100 returns: 0.012000000365078449
max of last 100: 0.10000000149011612
update 570/

In [ ]:
def copy_model_and_plot_learning_curve():
    import pickle
    import matplotlib.pyplot as plt
    from collections import deque
    import os
    import datetime
    import shutil
    
    datetime_stamp = datetime.datetime.now().strftime('%y%m%d_%H%M')
    plot_path = f'checkpoints/{datetime_stamp}'
    
    if not os.path.exists(plot_path):
        os.makedirs(plot_path)
    else:
        print(f'directory {plot_path} already exists')
        return
    
    shutil.copyfile(f'{brain_name}_scores.pickle', f'{plot_path}/scores.pickle')
    shutil.copyfile(f'{brain_name}_model_checkpoint.pickle', f'{plot_path}/model.pickle')

    with open(f'{plot_path}/scores.pickle', 'rb') as f:
        total_rewards = pickle.load(f)

    smoothed = []
    queue = deque([], maxlen=10)
    for r in total_rewards:
        queue.append(r)
        smoothed.append(sum(queue)/len(queue))
    fig,ax = plt.subplots()
    ax.plot(smoothed)
    ax.set_xlabel('total episodes (across all agents)')
    plt.savefig(f'{plot_path}/learning_curve.png')
    plt.show()
copy_model_and_plot_learning_curve()